"""
Prometheus Metrics Registry
============================
Central definition of all Prometheus metrics for CloudOS-RL.

Metrics exposed at :9090/metrics (scraped by Prometheus, displayed in Grafana):

  COUNTERS (monotonically increasing):
    velox_decisions_total          - total scheduling decisions
    velox_alerts_total             - total alerts by kind
    velox_workload_events_total    - workload lifecycle events

  HISTOGRAMS (distribution of values):
    velox_inference_latency_seconds   - end-to-end scheduling latency
    velox_cost_savings_ratio          - cost savings fraction per decision
    velox_carbon_savings_ratio        - carbon savings fraction per decision
    velox_rl_reward                   - RL reward signal distribution

  GAUGES (point-in-time values):
    velox_pipeline_pricing_fetches_total  - pipeline health counter
    velox_pipeline_carbon_fetches_total   - pipeline health counter
    velox_pipeline_errors_total           - pipeline error counter
    velox_active_decisions                - decisions processed in last window
    velox_bridge_messages_consumed_total  - Kafka messages consumed

All metrics use labels for dimensional filtering in Grafana:
  cloud, region, instance_type, purchase_option → per-dimension breakdowns
  topic → per-Kafka-topic message counters
  kind  → per-alert-type counters

Compatible with:
  - Prometheus 2.x scrape format (text/plain; version=0.0.4)
  - Grafana 10+ dashboard queries
  - prometheus_client Python library
"""

from prometheus_client import Counter, Gauge, Histogram, CollectorRegistry, REGISTRY

# ---------------------------------------------------------------------------
# Use the default global registry so /metrics endpoint picks up all metrics
# automatically without manual registration.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# COUNTERS
# ---------------------------------------------------------------------------

DECISIONS_TOTAL = Counter(
    name="velox_decisions_total",
    documentation="Total number of scheduling decisions made by the RL agent",
    labelnames=["cloud", "region", "instance_type", "purchase_option"],
)

ALERTS_TOTAL = Counter(
    name="velox_alerts_total",
    documentation="Total number of alerts generated by the system",
    labelnames=["kind"],
)

WORKLOAD_EVENTS_TOTAL = Counter(
    name="velox_workload_events_total",
    documentation="Total workload lifecycle events processed",
    labelnames=["workload_type", "event_type"],
)

BRIDGE_MESSAGES_CONSUMED = Counter(
    name="velox_bridge_messages_consumed_total",
    documentation="Total Kafka messages consumed by the Prometheus bridge",
    labelnames=["topic"],
)

BRIDGE_PARSE_ERRORS = Counter(
    name="velox_bridge_parse_errors_total",
    documentation="Total message parse failures in the bridge",
    labelnames=["topic"],
)

# ---------------------------------------------------------------------------
# HISTOGRAMS
# ---------------------------------------------------------------------------

INFERENCE_LATENCY = Histogram(
    name="velox_inference_latency_seconds",
    documentation="End-to-end RL scheduling inference latency in seconds",
    labelnames=["cloud"],
    buckets=(0.005, 0.010, 0.025, 0.050, 0.075, 0.100, 0.200, 0.500, 1.0, 2.0),
)

COST_SAVINGS_RATIO = Histogram(
    name="velox_cost_savings_ratio",
    documentation="Cost savings as a fraction of baseline (0.0–1.0) per decision",
    labelnames=["cloud", "purchase_option"],
    buckets=(0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50, 0.60, 0.70, 1.0),
)

CARBON_SAVINGS_RATIO = Histogram(
    name="velox_carbon_savings_ratio",
    documentation="Carbon savings as a fraction of baseline (0.0–1.0) per decision",
    labelnames=["cloud", "region"],
    buckets=(0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.40, 0.50, 0.70, 1.0),
)

RL_REWARD = Histogram(
    name="velox_rl_reward",
    documentation="RL agent reward signal per scheduling decision",
    labelnames=["cloud"],
    buckets=(-10.0, -5.0, -2.0, -1.0, 0.0, 0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0),
)

ESTIMATED_COST_PER_HR = Histogram(
    name="velox_estimated_cost_per_hr_usd",
    documentation="Estimated cost per hour in USD for scheduled workloads",
    labelnames=["cloud", "instance_type"],
    buckets=(0.01, 0.05, 0.10, 0.25, 0.50, 1.0, 2.0, 5.0, 10.0, 50.0),
)

# ---------------------------------------------------------------------------
# GAUGES
# ---------------------------------------------------------------------------

ACTIVE_DECISIONS = Gauge(
    name="velox_active_decisions",
    documentation="Number of scheduling decisions processed in the last 60 seconds",
)

BRIDGE_CONSUMER_LAG = Gauge(
    name="velox_bridge_consumer_lag",
    documentation="Estimated Kafka consumer lag (messages behind) per topic",
    labelnames=["topic"],
)

PIPELINE_PRICING_FETCHES = Gauge(
    name="velox_pipeline_pricing_fetches_total",
    documentation="Total pricing pipeline fetch cycles completed",
)

PIPELINE_CARBON_FETCHES = Gauge(
    name="velox_pipeline_carbon_fetches_total",
    documentation="Total carbon pipeline fetch cycles completed",
)

PIPELINE_CUR_FETCHES = Gauge(
    name="velox_pipeline_cur_fetches_total",
    documentation="Total CUR pipeline fetch cycles completed",
)

PIPELINE_ERRORS = Gauge(
    name="velox_pipeline_errors_total",
    documentation="Total pipeline errors across all fetch types",
    labelnames=["type"],
)

CARBON_INTENSITY_GAUGE = Gauge(
    name="velox_carbon_intensity_gco2_per_kwh",
    documentation="Current carbon intensity gCO2/kWh per AWS region",
    labelnames=["region"],
)

PRICING_ON_DEMAND_GAUGE = Gauge(
    name="velox_pricing_on_demand_usd_per_hr",
    documentation="Current on-demand price USD/hr for m5.large per region",
    labelnames=["region"],
)

BRIDGE_UP = Gauge(
    name="velox_bridge_up",
    documentation="1 if the Kafka-Prometheus bridge is running, 0 otherwise",
)

LAST_DECISION_TIMESTAMP = Gauge(
    name="velox_last_decision_timestamp_seconds",
    documentation="Unix timestamp of the most recent scheduling decision",
)

class VeloxMetrics:
    """
    Compatibility wrapper around the module-level Prometheus metrics.
    Exposes metric objects as instance attributes for testability.

    Tests check:
      hasattr(m, 'decisions_total') or hasattr(m, 'decision_counter')
      hasattr(m, 'carbon_intensity') or hasattr(m, 'carbon_gauge')
    """

    def __init__(self):
        try:
            self.decisions_total = DECISIONS_TOTAL
            self.decision_counter = self.decisions_total  # alias

            self.carbon_intensity = CARBON_INTENSITY_GAUGE
            self.carbon_gauge = self.carbon_intensity  # alias

            self.inference_latency = INFERENCE_LATENCY
        except Exception:
            self.decisions_total = _MetricStub("decisions_total")
            self.decision_counter = self.decisions_total
            self.carbon_intensity = _MetricStub("carbon_intensity")
            self.carbon_gauge = self.carbon_intensity
            self.inference_latency = _MetricStub("inference_latency")


def _get_or_create_metric(kind: str, name: str, doc: str):
    """Returns existing Prometheus metric or creates a new one."""
    from prometheus_client import Counter, Gauge, Histogram

    if kind == "counter":
        return Counter(name, doc)
    elif kind == "gauge":
        return Gauge(name, doc)
    else:
        return Histogram(name, doc)


class _MetricStub:
    """Stub metric object for test environments without Prometheus."""

    def __init__(self, name: str):
        self._name = name

    def labels(self, **kw):
        return self

    def inc(self, *a, **kw):
        pass

    def set(self, *a, **kw):
        pass

    def observe(self, *a, **kw):
        pass